import com.google.gson.Gson;
import io.undertow.Undertow;
import io.undertow.util.Headers;

import static java.util.Collections.singletonMap;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
      Gson gson = new Gson();
      Undertow.builder()
                .addHttpListener(8080, "localhost")
                .setHandler(exchange -> {
                    exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, "application/json");
                    exchange.getResponseSender().send(gson.toJson(singletonMap("message", "Hola!")));
                })
                .build()
                .start();
    }
}
